/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stores.management;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import stores.management.dao.ProductDao;
import stores.management.entity.Product;
import stores.management.entity.ProductFile;

/**
 *
 * @author anis
 */
public class productv extends javax.swing.JFrame {

    ProductDao pDao = new ProductDao();

    InputStream photo1;
    InputStream photo2;
    InputStream photo3;

    /**
     * Creates new form AddProduct
     */
    public productv() {
        initComponents();
    }

    private void closeResouces() {
        try {
            if (photo1 != null) {
                photo1.close();
            }

            if (photo2 != null) {
                photo2.close();
            }

            if (photo3 != null) {
                photo3.close();
            }

        } catch (Exception e) {

        }
    }

    private void clearFields() {
        lblFile1.setIcon(null);
        lblFile1.revalidate();
        lblFile1.setText("photo1");

        lblFile2.setIcon(null);
        lblFile2.revalidate();
        lblFile2.setText("photo1");

        lblFile3.setIcon(null);
        lblFile3.revalidate();
        lblFile3.setText("photo1");

        tfProductName.setText("");
        taProductDisc.setText("");
        tfProductLink.setText("");
    }

    private void fillTable() {
        List<Product> products = pDao.all();
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        model.setRowCount(0);
        for (Product p : products) {
            model.addRow(new Object[]{p.getId(), p.getName(), p.getDiscription(), p.getLink()});
        }
    }
    
    private void fillTable(String sName) {
        List<Product> products = pDao.all(sName);
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        model.setRowCount(0);
        for (Product p : products) {
            model.addRow(new Object[]{p.getId(), p.getName(), p.getDiscription(), p.getLink()});
        }
    }

    private void setValues(Product p) {
        tfProductName.setText(p.getName());
        taProductDisc.setText(p.getDiscription());
        tfProductLink.setText(p.getLink());
        try {
            if(p.getPhoto1() != null && p.getPhoto1().getPhoto() != null) {
                Image image = ImageIO.read(p.getPhoto1().getPhoto());
            ImageIcon icon = new ImageIcon(image);
            lblFile1.setText("");
            lblFile1.setIcon(new ImageIcon(icon.getImage().getScaledInstance(lblFile1.getWidth(),
                    lblFile1.getHeight(), Image.SCALE_SMOOTH)));
            }
            
            if(p.getPhoto2() != null && p.getPhoto2().getPhoto() != null) {
                Image image2 = ImageIO.read(p.getPhoto2().getPhoto());
            ImageIcon icon2 = new ImageIcon(image2);
            lblFile2.setText("");
            lblFile2.setIcon(new ImageIcon(icon2.getImage().getScaledInstance(lblFile2.getWidth(),
                    lblFile2.getHeight(), Image.SCALE_SMOOTH)));
            }
            
            if(p.getPhoto3() != null && p.getPhoto3().getPhoto() != null) {
                Image image3 = ImageIO.read(p.getPhoto3().getPhoto());
            ImageIcon icon3 = new ImageIcon(image3);
            lblFile3.setText("");
            lblFile3.setIcon(new ImageIcon(icon3.getImage().getScaledInstance(lblFile3.getWidth(),
                    lblFile3.getHeight(), Image.SCALE_SMOOTH)));
            }
            
        } catch (IOException ex) {
            Logger.getLogger(productv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attachFile1 = new javax.swing.JButton();
        attachFile2 = new javax.swing.JButton();
        attachFile3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfProductLink = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfProductName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taProductDisc = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblFile1 = new javax.swing.JLabel();
        lblFile2 = new javax.swing.JLabel();
        lblFile3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(705, 627));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                productv.this.windowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                productv.this.windowOpened(evt);
            }
        });

        attachFile1.setText("Attach");
        attachFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachFile1ActionPerformed(evt);
            }
        });

        attachFile2.setText("Attach");
        attachFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachFile2ActionPerformed(evt);
            }
        });

        attachFile3.setText("Attach");
        attachFile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachFile3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Product Name:");

        tfProductLink.setText("http://www.");
        tfProductLink.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Product Discription:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Product Link:");

        tfProductName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        taProductDisc.setColumns(20);
        taProductDisc.setRows(5);
        taProductDisc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        taProductDisc.setMaximumSize(new java.awt.Dimension(164, 94));
        taProductDisc.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setViewportView(taProductDisc);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblFile1.setText("Photo1");
        lblFile1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        lblFile1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFile1.setMaximumSize(new java.awt.Dimension(242, 162));
        lblFile1.setMinimumSize(new java.awt.Dimension(242, 162));
        lblFile1.setPreferredSize(new java.awt.Dimension(242, 162));

        lblFile2.setText("Photo2");
        lblFile2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        lblFile2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFile2.setMaximumSize(new java.awt.Dimension(242, 162));
        lblFile2.setMinimumSize(new java.awt.Dimension(242, 162));
        lblFile2.setPreferredSize(new java.awt.Dimension(242, 162));

        lblFile3.setBackground(new java.awt.Color(255, 255, 255));
        lblFile3.setText("Photo2");
        lblFile3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        lblFile3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFile3.setMaximumSize(new java.awt.Dimension(242, 162));
        lblFile3.setMinimumSize(new java.awt.Dimension(242, 162));
        lblFile3.setPreferredSize(new java.awt.Dimension(242, 162));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jScrollPane2.setMaximumSize(new java.awt.Dimension(420, 257));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(420, 257));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(420, 257));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Description", "Link"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnOpen)))
        );

        jButton1.setText("Go To Website");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attachFile3)
                            .addComponent(lblFile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfProductLink, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attachFile1)
                            .addComponent(lblFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(attachFile2)
                        .addGap(215, 215, 215)
                        .addComponent(jLabel6)))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(attachFile1)
                        .addGap(8, 8, 8)
                        .addComponent(lblFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(tfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attachFile2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attachFile3)
                        .addGap(6, 6, 6)
                        .addComponent(lblFile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfProductLink, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        btnSave.setVisible(true);
        closeResouces();
        clearFields();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void attachFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachFile1ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files",
                "jpg", "png", "gif", "jpeg");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();

        if (f != null) {
            try {
                photo1 = new FileInputStream(new File(f.getAbsolutePath()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(productv.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(f.toString());
            lblFile1.setText("");
            lblFile1.setIcon(new ImageIcon(icon.getImage().getScaledInstance(lblFile1.getWidth(),
                    lblFile1.getHeight(), Image.SCALE_SMOOTH)));
        }

    }//GEN-LAST:event_attachFile1ActionPerformed

    private void attachFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachFile2ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files",
                "jpg", "png", "gif", "jpeg");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();

        if (f != null) {
            try {
                photo2 = new FileInputStream(f);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(productv.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(f.toString());
            lblFile2.setText("");
            lblFile2.setIcon(new ImageIcon(icon.getImage().getScaledInstance(lblFile2.getWidth(),
                    lblFile2.getHeight(), Image.SCALE_SMOOTH)));
        }
    }//GEN-LAST:event_attachFile2ActionPerformed

    private void attachFile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachFile3ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files",
                "jpg", "png", "gif", "jpeg");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();

        if (f != null) {
            try {
                photo3 = new FileInputStream(f);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(productv.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon icon = new ImageIcon(f.toString());
            lblFile3.setText("");
            lblFile3.setIcon(new ImageIcon(icon.getImage().getScaledInstance(lblFile3.getWidth(),
                    lblFile3.getHeight(), Image.SCALE_SMOOTH)));
        }
    }//GEN-LAST:event_attachFile3ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code 
        
        ProductFile f1 = new ProductFile(photo1);
        ProductFile f2 = new ProductFile(photo2);
        ProductFile f3 = new ProductFile(photo3);

        Product p = new Product(tfProductName.getText(), taProductDisc.getText(),
                tfProductLink.getText(), f1, f2, f3);

        String s = pDao.add(p);
        JOptionPane.showMessageDialog(this, s);
        closeResouces();
        clearFields();
        fillTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void windowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowDeactivated
        // TODO add your handling code here:
        //closeResouces();

    }//GEN-LAST:event_windowDeactivated

    private void windowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpened
        // TODO add your handling code here:
        fillTable();

    }//GEN-LAST:event_windowOpened

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        btnSave.setVisible(false);
        int row = tblProduct.getSelectedRow();
        String value = tblProduct.getModel().getValueAt(row, 0).toString();
        long id = Long.parseLong(value);
        Product p = pDao.get(id);
        setValues(p);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchName = tfSearch.getText();
        if(searchName == null || searchName.equals("")) return;
        fillTable(searchName);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = tblProduct.getSelectedRow();
        String value = tblProduct.getModel().getValueAt(row, 0).toString();
        long id = Long.parseLong(value);
        
        String s = pDao.delete(id);
        JOptionPane.showMessageDialog(this, s);
        fillTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String link = tfProductLink.getText().trim();
        try {
            Desktop.getDesktop().browse(new URL(link).toURI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachFile1;
    private javax.swing.JButton attachFile2;
    private javax.swing.JButton attachFile3;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFile1;
    private javax.swing.JLabel lblFile2;
    private javax.swing.JLabel lblFile3;
    private javax.swing.JTextArea taProductDisc;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField tfProductLink;
    private javax.swing.JTextField tfProductName;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
